default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_tracker_api_db_dev
  host: localhost

test:
  <<: *default
  database: budget_tracker_api_db_test
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Utilizing the full DATABASE_URL provided by Railway

